server:
  port: 2022
  error:
    include-message: always
    include-binding-errors: always
# Spring Boot configuration
spring:
  application:
    name: spring-boot-hazelcast
  liquibase.change-log: "classpath:/db/changelog/master.xml"
  # Database
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:springboot-hazelcast
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        cach:
#          provider_class: com.hazelcast.hibernate.provider.HazelcastCacheProvider
#          region:
#            factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
#          use_second_level_cache: true
#          use_query_cache: true
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    database: H2
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    generate-ddl: true